import { CalendarDays, ChevronDown, FileText, HelpCircle, UsersRound } from 'lucide-react'
const icons = { file: FileText, users: UsersRound, calendar: CalendarDays, help: HelpCircle }

export function GeneralInformationSection({ content }) {
  return <section id="informacion-general" className="scroll-mt-28 border-b border-line py-16 sm:py-20" aria-labelledby="titulo-informacion-general"><div className="mx-auto max-w-content px-5 sm:px-8">
    <div className="grid gap-10 lg:grid-cols-[0.65fr_1.35fr] lg:gap-16"><div><p className="eyebrow text-brand-primary">{content.eyebrow}</p><h2 id="titulo-informacion-general" className="section-title mt-3">{content.title}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-700">{content.description}</p></div><nav aria-label="Temas de información general"><ol className="border-y border-line">{content.routes.map((route, index) => { const Icon = icons[route.icon] || HelpCircle; return <li className="border-b border-line last:border-b-0" key={route.key}><a className="group grid min-h-32 grid-cols-[auto_1fr_auto] items-center gap-4 py-5" href={route.href} aria-label={route.label} {...(route.external ? { rel: 'noopener noreferrer', target: '_blank' } : {})}><span className="text-sm font-black text-brand-primary/60">{String(index + 1).padStart(2, '0')}</span><span><span className="flex items-center gap-3 text-xl font-black text-slate-900 group-hover:text-brand-primary"><Icon aria-hidden="true" className="shrink-0 text-brand-primary" size={22}/>{route.title}</span><span className="mt-2 block max-w-2xl leading-7 text-slate-600">{route.description}</span></span><span aria-hidden="true" className="text-2xl text-brand-primary">→</span></a></li>})}</ol>{content.routes.length === 0 && <p className="py-6 text-slate-600">No hay rutas informativas publicadas.</p>}</nav></div>
    <div id="preguntas-frecuentes" className="mt-14 scroll-mt-28 border-t-4 border-brand-highlight pt-8"><div className="grid gap-8 lg:grid-cols-[0.65fr_1.35fr] lg:gap-16"><div><p className="eyebrow text-brand-primary">{content.faq_eyebrow}</p><h3 className="mt-3 text-2xl font-black text-slate-900">{content.faq_title}</h3></div><div className="divide-y divide-line border-y border-line">{content.faqs.map(({ answer, key, question }) => <details className="group py-5" key={key}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-4 font-black text-slate-900 marker:hidden">{question}<ChevronDown aria-hidden="true" className="shrink-0 text-brand-primary transition-transform group-open:rotate-180 motion-reduce:transition-none" size={21}/></summary><p className="max-w-3xl pb-2 pr-10 leading-7 text-slate-700">{answer}</p></details>)}{content.faqs.length === 0 && <p className="py-6 text-slate-600">No hay preguntas frecuentes publicadas.</p>}</div></div></div>
  </div></section>
}
