function InstitutionLogo({ institution }) {
  if (!institution.logo_url) return null
  const image = <img alt={`Logotipo de ${institution.name}`} className="h-32 w-full object-contain sm:h-36 lg:h-32 xl:h-36 motion-safe:transition-transform motion-safe:duration-300 motion-safe:ease-out motion-safe:group-hover:scale-[1.06]" height={institution.logo_height || 500} loading="lazy" src={institution.logo_url} width={institution.logo_width || 500}/>
  return institution.url ? <a aria-label={`Visitar el sitio de ${institution.name}`} className="w-full" href={institution.url} rel="noopener noreferrer" target="_blank">{image}</a> : image
}

export function PartnersSection({ content }) {
  return <section id="colaboradores-patrocinadores" className="scroll-mt-28 border-b border-line py-16 sm:py-20" aria-labelledby="titulo-colaboradores"><div className="mx-auto max-w-content px-5 sm:px-8">
    <div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:gap-16"><div><p className="eyebrow text-brand-primary">{content.eyebrow}</p><h2 id="titulo-colaboradores" className="section-title mt-3">{content.title}</h2></div><p className="max-w-3xl text-lg leading-8 text-slate-700">{content.description}</p></div>
    <div className="mt-12" aria-labelledby="titulo-instituciones-colaboradoras"><div className="flex flex-col gap-2 border-b border-line pb-5 sm:flex-row sm:items-end sm:justify-between"><h3 id="titulo-instituciones-colaboradoras" className="text-2xl font-black text-slate-900">{content.collaborators_title}</h3><p className="text-sm font-bold uppercase tracking-[0.08em] text-brand-primary">{content.collaborators_note}</p></div><ul className="grid grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-3 lg:grid-cols-5 lg:gap-x-6" aria-label="Instituciones colaboradoras">{content.collaborators.map((institution) => <li className="group flex min-h-48 items-center justify-center px-3 py-5" key={institution.key}><InstitutionLogo institution={institution}/>{!institution.logo_url && <span className="text-center font-bold text-slate-700">{institution.name}</span>}</li>)}</ul></div>
    <div className="mt-12"><h3 className="text-2xl font-black text-slate-900">{content.sponsors_title}</h3><div className="mt-5 grid gap-6 lg:grid-cols-2">{content.sponsors.map((institution) => <article className="grid gap-5 border-l-4 border-brand-highlight bg-slate-50 px-6 py-7 sm:grid-cols-[10rem_1fr] sm:px-8" key={institution.key}><div className="group flex min-h-28 items-center justify-center"><InstitutionLogo institution={institution}/></div><div className="self-center"><h4 className="text-xl font-black text-slate-900">{institution.name}</h4>{institution.description && <p className="mt-3 leading-7 text-slate-700">{institution.description}</p>}</div></article>)}</div>{content.sponsors.length === 0 && <p className="mt-5 text-slate-600">No hay patrocinadores publicados en este momento.</p>}</div>
  </div></section>
}
