export const regionalCoordinations = [
  { region: 'Alajuela', contacts: [{ name: 'Lizbeth Arguedas Solera', emails: ['lizbeth.arguedas.solera@mep.go.cr'] }] },
  { region: 'Cañas', contacts: [{ name: 'Laura Patricia Briceño Cabezas', emails: ['laura.briceno.cabezas@mep.go.cr'] }] },
  { region: 'Cartago', contacts: [{ name: 'Ana María Navarro Ceciliano', emails: ['ana.navarro.ceciliano@mep.go.cr'] }] },
  { region: 'Coto', contacts: [{ name: 'Marvin Montiel Araya', emails: ['marvin.montiel.araya@mep.go.cr'] }] },
  { region: 'Central del Pacífico', contacts: [{ name: 'Marilú Rodríguez Mora', emails: ['marilu.rodriguez.mora@mep.go.cr'] }] },
  { region: 'Desamparados', contacts: [{ name: 'Yamil Fernández Martínez', emails: ['yamil.fernandez.martinez@mep.go.cr'] }] },
  { region: 'Grande de Térraba', contacts: [{ name: 'Corry Castillo Castillo', emails: ['corry.castillo.castillo@mep.go.cr'] }] },
  { region: 'Guápiles', contacts: [{ name: 'Luis Mena Esquivel', emails: ['luis.mena.esquivel@mep.go.cr'] }] },
  {
    region: 'Heredia',
    contacts: [
      { name: 'Mauren Oviedo Rodríguez', emails: ['maureen.oviedo.rodriguez@mep.go.cr'] },
      { name: 'Allan Pérez Calderón', emails: [] },
    ],
  },
  { region: 'Liberia', contacts: [{ name: 'Gualberto Morales Marenco', emails: ['gualberto.morales.marenco@mep.go.cr'] }] },
  { region: 'Limón', contacts: [{ name: 'Morris Antonio Domenech Castro', emails: ['morris.domenech.castro@mep.go.cr'] }] },
  { region: 'Los Santos', contacts: [{ name: 'Laura Andrea Ureña Ureña', emails: ['laura.urena.urena@mep.go.cr'] }] },
  { region: 'Nicoya', contacts: [{ name: 'Julissa Solís Umaña', emails: ['julisa.solis.umana@mep.go.cr'] }] },
  { region: 'Occidente', contacts: [{ name: 'Marjorie Rodríguez Soto', emails: ['marjorie.rodriguez.soto@mep.go.cr'] }] },
  { region: 'Peninsular', contacts: [{ name: 'Rodolfo Ovares Elizondo', emails: ['rodolfo.ovares.elizondo@mep.go.cr'] }] },
  { region: 'Pérez Zeledón', contacts: [{ name: 'Henry Campos Monge', emails: ['henry.campos.monge@mep.go.cr'] }] },
  { region: 'Puntarenas', contacts: [{ name: 'Cristian Barrientos Quesada', emails: ['cristian.barrientos.quesada@mep.go.cr'] }] },
  { region: 'Puriscal', contacts: [{ name: 'Ana Yancy Quirós Segura', emails: ['yancy.quiros.segura@mep.go.cr'] }] },
  { region: 'San Carlos', contacts: [{ name: 'Erika Méndez Céspedes', emails: ['erika.mendez.cespedes@mep.go.cr', 'dresc.asesoriamatematicas@mep.go.cr'] }] },
  { region: 'San José Central', contacts: [{ name: 'Kevin Adrián Rodriguez Alvarado', emails: ['kevin.rodriguez.alvarado@mep.go.cr'] }] },
  { region: 'San José Norte', contacts: [{ name: 'Alejandro López Solórzano', emails: ['alejandro.lopez.solorzano@mep.go.cr'] }] },
  { region: 'San José Oeste', contacts: [{ name: 'Marielos Rocha Palma', emails: ['marielos.rocha.palma@mep.go.cr'] }] },
  { region: 'Santa Cruz', contacts: [{ name: 'Krystel Fernández Castillo', emails: ['krystel.fernandez.castillo@mep.go.cr'] }] },
  { region: 'Sarapiquí', contacts: [{ name: 'Fabián Guillermo Zúñiga Arias', emails: ['fabian.zuniga.arias@mep.go.cr'] }] },
  { region: 'Sulá', contacts: [{ name: 'Ileana Lezcano Rodríguez', emails: ['ileana.lezcano.rodriguez@mep.go.cr'] }] },
  { region: 'Turrialba', contacts: [{ name: 'Javier Quirós Paniagua', emails: ['javier.quiros.paniagua@mep.go.cr'] }] },
  { region: 'Zona Norte Norte', contacts: [{ name: 'Edward Luna Ordóñez', emails: ['edward.luna.ordonez@mep.go.cr'] }] },
]
